// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDacuRKHZQ15zFS4XmPDtSjno-3mdNGypc',
    appId: '1:283986758714:web:3d07534931d527fa107903',
    messagingSenderId: '283986758714',
    projectId: 'calendar-application-bfe33',
    authDomain: 'calendar-application-bfe33.firebaseapp.com',
    storageBucket: 'calendar-application-bfe33.firebasestorage.app',
    measurementId: 'G-95MR0HXWZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcTKOOTNaK0ljNtgVCkwkR_HKgiUdKWog',
    appId: '1:283986758714:android:7e84b046e3b30f56107903',
    messagingSenderId: '283986758714',
    projectId: 'calendar-application-bfe33',
    storageBucket: 'calendar-application-bfe33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACEfmbbEykytVJn8R-JmuHZw_FimN3DQ8',
    appId: '1:283986758714:ios:3c765ae89ffc616c107903',
    messagingSenderId: '283986758714',
    projectId: 'calendar-application-bfe33',
    storageBucket: 'calendar-application-bfe33.firebasestorage.app',
    iosBundleId: 'com.example.calendarApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACEfmbbEykytVJn8R-JmuHZw_FimN3DQ8',
    appId: '1:283986758714:ios:3c765ae89ffc616c107903',
    messagingSenderId: '283986758714',
    projectId: 'calendar-application-bfe33',
    storageBucket: 'calendar-application-bfe33.firebasestorage.app',
    iosBundleId: 'com.example.calendarApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDacuRKHZQ15zFS4XmPDtSjno-3mdNGypc',
    appId: '1:283986758714:web:12117b034a1bd26a107903',
    messagingSenderId: '283986758714',
    projectId: 'calendar-application-bfe33',
    authDomain: 'calendar-application-bfe33.firebaseapp.com',
    storageBucket: 'calendar-application-bfe33.firebasestorage.app',
    measurementId: 'G-85LDD2YZSP',
  );

}